### ISSUE TITLE
Schiff verschwunden

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#102]
Aus dem Forum: https://forum.stuniverse.de/viewtopic.php?f=9&t=87
 Beitrag von sgt_dillard » Mo Dez 02, 2019 3:41 pm
in der Version 830 habe ich 2 Transportschiffe (ID's 984 und 985) auf meinem Mond mit der ID 2976 landen wollen und eins wird mir in dem Hangar des Flugfeldes nur noch eines der Schiffe angezeigt während im Lager der Kolonie 102 K-Frachter angezeigt werden

--------------------------------
Dass nur jeweils ein Schiff welches gestartet werden kann im Hangar angezeigt wird, ist korrekt. Jedoch die Tatsache dass er 102 Schiffe im Lager hatte nachdem er zwei Frachter gelandet hatte, sollte nicht sein. Ich hab den Wert bei ihm korrigiert, konnte den Fehler selbst aber nicht reproduzieren.

**Comment by usox** [comment]
Wurde vermutlich auch mit 38a1c47896a73aeaf0a6628a0e622efebf4d3277 behoben
