### ISSUE TITLE
Bonusfelder und Terraforming

### ISSUE THREAD

**Issue by LWU86** [st-universe/core#1031]
Aus dem Discord:

Es scheint, als könne auf einem Wasserfeld mit hoher Deuteriumkonzentration nach dem Aufschütten kein Gebäude gebaut werden.
Bitte mal drüber schauen, ob die Abhängigkeiten bei terraformten Feldern nicht vielleicht generell Ärger machen.

**Comment by Huxinator** [comment]
fixed
