### ISSUE TITLE
Aegian-Klasse

### ISSUE THREAD

**Issue by LWU86** [st-universe/core#114]
Die Aegian-Klasse scheint irgendwie verbuggt zu sein. Wenn ich die bauen will, wird der entsprechende Button nicht aktiv, obwohl alle Modulplätze belegt sind. (1er und 2er im Mix). Das Problem tritt sowohl in der Alpha als auch in der Dev auf.

Es liegt auch ziemlich sicher an der Klasse und nicht am Schiffbau an sich, da ich mit der Epsilon keine Probleme hatte und die Saber von Hux ja auch schon durch die Gegend düst.

**Comment by Huxinator** [comment]
Bei anderen Schiffsklassen (Epsilon, Saber habe ich ausprobiert) besteht der Fehler ebenfalls. Zumindest jetzt.
Heißt dass der Bug irgendwann nach dem Bau der von Fenian angesproghenenen Schiffe aufgetaucht sein muss.
