### ISSUE TITLE
E-Mail notification funktioniert nicht

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#130]
Titel sagt schon alles. Wenn man in den Einstellungen einen haken bei der notification hat und eine Privatnachricht im Spiel erhält, dann bekommt man keine E-Mail mit der jeweiligen Info dass man eine Nachricht bekommen hat.

**Comment by Huxinator** [comment]
Mir stellt sich die Frage, ob diese Funktion überhaupt noch nützlich ist? Sicher gerade heutzutage bekommt man übers Handy viel schneller E-Mail Benachrichtigungen als push-up usw. Aber alles in allem ist man doch nicht so selten in STU dass man nicht an einem Tag mal mitbekommt wenn eine Nachricht im Postfach gelandet ist. Und wenn man mal eher seltener in STU ist, dann hat das wohl Gründe und gerade dann will man doch auch nicht zwingend mit Mails vollgespamt werden oder?

**Comment by usox** [comment]
Ich halte die Funktion fuer durchaus sinnvoll, gerade in den von Dir beschriebenen Faellen. Ich bin z.B. definitiv mal ein paar Tage nicht eingeloggt (ich vergess es im Stress schlichtweg) und da ists schon gut, wenn man mal ne Info bei privaten Nachrichten kriegen kann.

Davon ab: Das ist im Moment noch nichtmal eingebaut :D
Ich werde das mal Ingame ausblenden und nen Enhancment draus machen
