### ISSUE TITLE
Schiff/Kolo-name/grafik sollte weiterleiten

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#135]
Allgemein nützlich wäre es wenn man wieder nur durch klicken auf den Schiffsnamen/Schiffsgrafik bspw. in den Nahbereichsensoren von Schiffen oder im Koloniemanagment auf das jeweilige Schiff weitergeleitet werden kann ohne umständlich ins Schiffsmenü rüber zu gehen.

Selbiges würde vieles auch bei den Kolonien vereinfachen wenn man dort wo der Koloname auftaucht also neben der Koloübersicht eigentlich nurnoch in den Nahbereichsensoren des Schiffes durch einfaches klicken auf das Bild oder den Kolonamen auf die jeweilige Kolonie umgeleitet werden würde.

**Comment by LWU86** [comment]
Also vom Schiff aus kommt man direkt auf die Kolonie. Ein Klick auf den Namen oder die kleine Planetengrafik daneben und schon ist man da. 

Aber ja, wieder direkt zu den Schiffen springen zu können, wäre sehr angenehm.
