### ISSUE TITLE
Aktuelle Datenbank

### ISSUE THREAD

**Issue by Zurret** [st-universe/core#1449]
Gibt es eine Möglichkeit dass das Backup von der Datenbank ein kleines Update bekommt? 
Es wurde ja mittlerweile viel geändert und leider sind diese Änderungen nicht im aktuellen Dump. (z.b das mit dem starsystem_map_id)
Bei einer frisch Installierten Entwicklungsumgebung local sind alle Kolonien/Planeten nicht zugeordnet.

Ach und https://github.com/st-universe/core/blob/794f455d51874c6de2170684622aa6d859fe6adb/src/Lib/BuildMenu.php#L28 da ist ein `;` statt ein `:`

**Comment by Huxinator** [comment]
Aktuell nicht

**Comment by AngelandDevil** [comment]
Servus :-) Ist in geraumer Zeit mit einem Update der DB gepant oder generell eher nicht? Ich habe mich ein wenig mit der DEV Umgebung beschäftigt nur leider wegen der Veilzahl an DB Änderungen komm ich nicht zum finalen Erfolg.

**Comment by Huxinator** [comment]
Es ist zeitnah nicht geplant. Müssten dafür für einen sauberen dump einmal aus dem Live Spiel die db nehmen, kopieren, resetten, die saubere db hier exportieren und das backup wieder einspielen. Das würd vermutlich etwas Zeit in Anspruch nehmen (plus minus Komplikationen) was letztendlich das live Spiel stört.

**Comment by AngelandDevil** [comment]
Versteh ich absolut. Danke für die ausführliche Info.

**Comment by Zurret** [comment]
Hab mir die DB mal schnell selbst grob gefixt, muss nur noch die fehlenden Sachen hinzufügen.

**Comment by Huxinator** [comment]
Wenn aber jemand einen gefixten dump hat, also vermutlich nur eher die Tabellen aber nicht alle möglichen Daten, dann wären sicher hier einige Dankbar für ein Upload :D Geht ja bei vielen als aller erstes da drum, das Spiel überhaupt zum laufen zu bekommen.

**Comment by Zurret** [comment]
Klar.

Hier gibt's den Backup: https://anonfiles.com/Z2e8y4V3x1/backup_sql

**Comment by sebastianreinig** [comment]
@Zurret Kannst du das File noch Mal hochladen? Ist leider nicht mehr verfügbar.

> Klar.
> 
> Hier gibt's den Backup: https://anonfiles.com/Z2e8y4V3x1/backup_sql

Kannst du das noch Mal hochladen? Ist leider nicht mehr verfügbar. Danke!

**Comment by Zurret** [comment]
Die Seite führt aktuell Wartungsarbeiten durch, vorhanden ist sie noch.

**Comment by PazBorma** [comment]
Aktuell kommt die Meldung, dass die Datei nicht existiert.
