### ISSUE TITLE
Schiffswracks sollten diverse Schiffs-Aktionen nicht unterstützen

### ISSUE THREAD

**Issue by usox** [st-universe/core#20]
Derzeit ist es so, dass man mit Wracks diverse Dinge treiben kann, die keinen Sinn machen (z.b. Traktorstrahl). Man muss da mal schauen, was mit einem Wrack alles möglich sein soll oder was nicht und das dann auch technisch verhindern

**Comment by LWU86** [comment]
Runterbeamen, Scannen und drauf schießen. Mehr scheint mir keinen Sinn zu machen.

**Comment by usox** [comment]
Draufbeamen könnte auch spannend sein ;)
