### ISSUE TITLE
Forschungsbeschreibungen

### ISSUE THREAD

**Issue by usox** [st-universe/core#21]
Ich denke, eine der wichtigsten Content-Themen im Moment stellen die Forschungs-Beschreibungen dar. Gerade Spieler, die hier in der StarTrek Welt nicht so fit sind, stehen ein wenig wie `der Ochs vorm Berg`. Man sollte hier also mal anfangen, jeder Forschung eine kleine Beschreibung zu spendieren. Es ist auch ein Bild pro Forschung vorgesehen, aber das hat jetzt keine Prioritaet.
Idealerweise faengt man mal bei den Einstiegs-Forschungen an und hangelt sich durch - das ganze als maschinenlesbare Datei mit Id der Forschung und Text waere perfekt.

**Comment by Huxinator** [comment]
https://1drv.ms/x/s!AtzC9TonYBBtkQhHn1OUb5LrG9WF
Wer sich dran beteiligen möchte kann dies gern in dieser Datei tun

**Comment by usox** [comment]
Na wenn da mal nich das Encoding kaputt gegangen ist... ;)

**Comment by Huxinator** [comment]
Sollte durch sein
