### ISSUE TITLE
Sicherheitsabfrage bei Kolonieaufgabe

### ISSUE THREAD

**Issue by LWU86** [st-universe/core#277]
Damit das nicht untergeht:
Im Discord kam der dringende Vorschlag, eine Sicherheitsabfrage einzubauen, wenn man eine Kolonie aufgibt,
Momentan gibts die nicht und gerade aufm Handy kommt man da wohl schneller mal versehentlich gegen.

**Comment by Huxinator** [comment]
1fbcfb3
