### ISSUE TITLE
2-Factor Authentifizierung bei Registrierung

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#29]
Um zukünftig Multis zu vermeiden, sollte man eine 2-Factor Authentifizierung bei der Registrierung einbauen. Indem man bspw. seine Handynummer bei der Registrierung angeben muss, erhält man zur Freischaltung einen Code per SMS um die Registrierung abzuschließen.

Die Handynummer würde dann verschlüsselt zum Account gespeichert werden und bei Neuregistrierungen abgeglichen werden. Sicherlich besteht immer noch die Möglichkeit, dass irgendwelche Freaks sich eine zweite SIM Karte mal eben für 10 Euro kaufen o.ä. Dennoch macht es das schwerer mit Multis zu spielen. Zumal mal eben die IP über VPN wechseln oder direkt übern Router wechseln, mittlerweile jeder normalo kann (#dankeGeoblocking :D)

**Comment by Bielhelm** [comment]
Ich gehe davon aus, daß so ein Überwachungssystem erst dann Sinn machen wird, wenn STU 3 beta läuft. Die zweifache Registrierung beinhaltet diverse Fremdtechnologien, die man schwer selbst entwickeln oder implementieren kann. Wir wissen auch noch nicht, ob STU 3 Beta überhaupt ein Erfolg wird.

**Comment by usox** [comment]
Das ist etwas, worueber mal sprechen wird, wenn wirklich mal ein Bedarf besteht.
