### ISSUE TITLE
[question] make DB not working

### ISSUE THREAD

**Issue by wumix** [st-universe/core#298]
make dev-create-db

docker-compose up stu-db -d
```
`ERROR:` No such service: -d
make: *** [Makefile:30: dev-create-db] Error 1
```

**Comment by Saboti** [comment]
Hi wumix,
der Command ist falsch.
Richtig: docker-compose up -d stu-db
Allerdings hänge ich am Befehl danach :(

**Comment by Zurret** [comment]
Das ganze funktioniert übrigens auch ohne Docker ^^
@Saboti einmal `vendor/bin/doctrine orm:generate-proxies` ausgeführt?

**Comment by wumix** [comment]
Yes perfekt ich danke euch

**Comment by Saboti** [comment]
> Das ganze funktioniert übrigens auch ohne Docker ^^
> @Saboti einmal `vendor/bin/doctrine orm:generate-proxies` ausgeführt?

Danke das hatte gefehlt. Ist durchgelaufen danach. Glaube jetzt hab ich noch ein Fehler in der Config. Er zeigt mir auf der Webseite direkt die Fehlerseite an.

**Comment by Zurret** [comment]
`debug_mode` auf true setzen dann siehst du auch eine Fehlermeldung
Das machst du in der config.json

**Comment by Saboti** [comment]
Danke, hatte den webroot Pfad falsch.
Jetzt läuft es. Als letztes brauche ich noch ein Tipp mit dem Admin Zugang :)

**Comment by Saboti** [comment]
@Zurret hast Du mir noch ein Tipp. Nach dem Login wird die Oberfläche nicht richtig Angezeigt. Das css & ja wird wohl nicht geladen. Hab was mit Version im Quelltext gefunden, verstehe aber nicht woran genau es hängt :)

**Comment by Zurret** [comment]
@Saboti Version in der config.json auf dev stellen und in Public einen verlinkten Ordner erstellen wie im der make File vorgegeben `cd src/Public && ln -s . version_dev`

**Comment by usox** [comment]
Aktuell wieder lauffähig wie in der readme beschrieben
