### ISSUE TITLE
Newbie Frachter

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#31]
Wie bereits in #4 besprochen wollen wir eine Art Newbie Frachter erstellen. Dieser soll:

- Ein relativ großen Lagerraum haben
- Ohne Crew fliegen können
- Über einen Deuteriumreaktor laufen
- Nicht Warpfähig sein
- Nicht von anderen Schiffen etwas weg beamen können sondern nur über die Kolonie beamen können
- Früh erforscht werden können (am besten zur selben Zeit wie ein Icarus Shuttle)

Dazu muss gemacht werden:
- Ein neuer Rumpf muss in der DB erstellt werden
- Neues spezialmodul (Beamschutz) muss erstellt werden
- Neuer Deuteriumreaktor muss erstellt werden
- Neue Forschung muss in der DB erstellt werden
- Grafik und Namen für den Frachter
- Grafik für ein Deuteriumreaktor Icon

**Comment by usox** [comment]
Grundsätzliche Idee ist:
- Spezielles EPS-Modul mit neuem Effekt "Nicht beamfähig"
- Neues Reaktor-Modul für den Betrieb mit Deuterium

**Comment by Huxinator** [comment]
Die Frachter wurden erstellt und auch in den Forschungsbaum eingepflegt.
Es fehlen nurnoch die Spezialmodule.

**Comment by usox** [comment]
Also ich habe ein wenig überlegt.
Welchen Sin macht es, wenn das Schiff nur mit Deuterium betrieben werden kann und  nicht warpfähig ist? Jedes Schiff, welches für Spieler baubar ist, ist warpfähig. Die ganz einfachen Schiffe (die landbaren) brauchen auch keine Warpkernladung, können dennoch regulär genutzt werden - warum also auch nicht der Frachter?
Der Aufwand, jetzt nur für diesen Zweck einen Deuterium-Reaktor zu bauen, steht nicht im Verhältnis zum Nutzen. Daher würde ich mich mehr auf das EPS-Modul konzentrieren.
Vermutlich wäre es sinnvoll, die Beam-Effizienz (Energie pro Wareneinheit) an das EPS-Modul zu koppeln - Diebstahl wäre demnach nur unter hohem Energieaufwand möglich und lohnt sich daher nicht.
Ich würde daher auch dazu tendieren, Reaktorleistung und Energiespeicher stark zu senken (vielleicht mal so um 40% oder so) mit dem Ziel, daraus wirklich einen Kurzstreckenfrachter zu machen. Man schaffts vielleicht auch noch zum nächsten Handelsposten, braucht aber zeit...

**Comment by Bielhelm** [comment]
Ähnliche Ideen wurden in 2.6 umgesetzt, (drastische Senkung von Warpkernreichweiten, Abkopplung von Energie im System) aber leider für alle Schiffe. Solange es nur bei einfachen Frachtern bliebt : OK. Die Spieler dort finden es sonst schade. Das Rumdüsen in der Ausdehnung ist das interessanteste auf der Karte, was man manchen kann. Aber die Frage wäre eigentlich an das Balancing Team zu stellen?

**Comment by usox** [comment]
Da es hier nur um den Frachter geht, sind auch keine anderen Schiffe betroffen. Schiffe sollen ihrer Rolle gerecht werden und ein Kurzstreckenfrachter ist nunmal kein Forschungsschiff.

@Bielhelm Ich denke es wäre zudem sinnvoll, nicht ständig die `In <anderes spiel ist es aber so>` als Argument bzw. Diskussionspunkt rauszuholen.

**Comment by Huxinator** [comment]
@usox der Frachter sollte mMn deshalb mit Deuterium betrieben werden können, da die Erforschung und Produzierung von Deuterium relativ früh durch den frühen Eintrag im Forschungsbaum anlaufen kann. Ziel ist es ja, den Spielern so früh wie möglich einen Frachter zu geben, welcher die ersten zwei Kolonien versorgen kann. Mit einem Deuteriumreaktor ist sowas möglich. Jedoch so lang zu warten, bis man noch Teilchenbeschleuniger erforscht und gebaut hat um WK Ladung zu produzieren halte ich nicht für zielführend.

**Comment by usox** [comment]
@Huxinator Wenn wir den Frachter so handhaben wie z.b.die Icarus, stellt sich das Problem nicht. Gestartet wird das Schiff mit einem `vollen` Warpkern. Landet man es und startet man es, ist er wieder voll - ganz ohne Antimaterie/Deuterium Geschiebe. Hat man Deut/Antimaterie dann, kann man den Warpkern im Nachhinein auch wieder selbst laden.
Man koennte den Start von Schiffen natuerlich insofern erweitern, dass der Start Deuterium kostet (und nicht der Bau wie bei der Icarus)

**Comment by LWU86** [comment]
Das fände ich ziemlich gut @usox. Ist ne einfache und doch elegante Lösung - wesentlich besser, als nen extra Modul dafür zu kreieren.

**Comment by Huxinator** [comment]
Ich mach mal das Thema wieder auf, da @LWU86 und mir gerade eine Idee gekommen ist.
Um das Problem mit der Crew am Anfang zu lösen haben wir uns gedacht, die Crew wieder auf 0 für den Frachter wieder zu reduzieren. Aber um nun keine Anzahl an unendlichen Schiffen zu generieren (was ja theoretisch möglich wäre) müsste man es so einstellen, dass maximal ein Schiff dieser Klasse überhaupt gestartet werden kann. Ich weiß dass diese Funktion bei Kolonisationsschiffen existiert. Ich geh mal davon aus, dass es schlicht an dem Kolonisationsmodul gekoppelt ist. Mein Vorschlag wäre, dass man ein Modul entwickelt, welches halt nur dazu da ist, dass man nur eins dieser Schiffe starten kann. Sollte doch umsetzbar sein oder @usox ?

**Comment by Bielhelm** [comment]
Die Kolonie-Zentrale könnte aber diese Crewmitglieder sehr niedrigen Standes als Crew fuer diesen Frachter generieren, dann waeren alle diese Überlegungen nicht notwendig. 

Crews werden besser, je mehr diese in die Schule gehen. Aber nicht aus jedem Anfangsfrachterkapitän sollte auch ein Starship Kapitän werden können. 

Man sollte aber im Zuge dessen seine Crew auch entlassen oder verkaufen können.

**Comment by Huxinator** [comment]
> 
> 
> Die Kolonie-Zentrale könnte aber diese Crewmitglieder sehr niedrigen Standes als Crew fuer diesen Frachter generieren, dann waeren alle diese Überlegungen nicht notwendig.
>

Nein. Dann müsste die Koloniezentrale nicht nur die Werte erzeugen sondern auch die Funktion haben um Crew auszubilden. Wenn die Koloniezentrale das hat, wäre ein Akademiegebäude momentan unnötig.

> 
> Crews werden besser, je mehr diese in die Schule gehen. Aber nicht aus jedem Anfangsfrachterkapitän sollte auch ein Starship Kapitän werden können.
> 
> Man sollte aber im Zuge dessen seine Crew auch entlassen oder verkaufen können.
>

Falsches Issue für diese Ideen.

**Comment by usox** [comment]
> Der Vorschlag wäre, dass man ein Modul entwickelt, welches halt nur dazu da ist, dass man nur eins dieser Schiffe starten kann. Sollte doch umsetzbar sein oder @usox ?

Moeglich sicher, aber ich finde es nicht gut. So etwas erzeugt nur Komplexitaet fuer einen quasi nicht vorhandenen Nutzen (es ist nur ein Workaround). Solche Probleme gilt es mit Konfiguration oder sinnigen Anpassungen zu beheben.

Ehrlich gesagt sehe ich hier mehrere Moeglichkeiten:
- Man zieht die Akademie im Forschungsbaum nach vorne (z.b. nach Flugfeld)
- Man erlaubt die Ausbildung von Crew an der Koloniezentrale; im Hinblick auf spaeter koennte man sagen: Koloniezentrale kann nur Crewmen, fuer die Weiterbildung braucht man spaeter eine Akademie
- Man laesst jeden Siedler mit der Menge Crew starten, die der Frachter benoetigt

**Comment by LWU86** [comment]
Der letzte Punkt wäre wohl am einfachsten und auch am sinnvollsten. Immerhin müssen die Kolonisten ja auch irgendwie auf ihre Planeten gekommen sein. Schon denkbar, daß sich da jemand mit Raumschiffen auskennt ;)

**Comment by usox** [comment]
Das Thema wurde nun ja durchgekaut und man hat soweit eine Loesung erzielt. Daher mache ich das Thema hier mal dicht
