### ISSUE TITLE
Allianz Territorien

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#37]
Ich weiß zwar momentan nicht genau wo die Grenzen der großen Mächte gezogen werden bzw. wie viel unbenaspruchter Raum existiert. Aber mein Vorschlag wäre, neben den Territorien der großen Fraktionen auch den jeweiligen Allianzen Territorien zuzusprechen.

Diese Territorien sollten variabel sein und könnten bspw. entweder davon abhängen zu wie viel % ein Siedler einer Allianz ein gewisses System besiedelt hat. Sollte eine Allianz einen prozentual höheren Anteil an einem System haben, als andere Siedler die dort ggf. siedeln, wird das System automatisch dieser Allianz zugesprochen und wenn möglich irgendwo kenntlich gemacht. Möglich wäre es auch, einige Kartenfelder um dieses System herrum dann einer Allianz zu zu sprechen, damit eine Allianz ggf. Systeme territorial verbinden kann. Falls Kolonien ausbomben usw. geplant ist, könnte man natürlich auch durch soetwas seine Territorien wieder verlieren.

Eine andere Idee wäre, die Systeme einer Allianz nach der Anzahl der Schiffe oder eben der Anzahl der Schiffspunkte in dem System zuzuweisen. Jedoch verlassen Schiffe gerne mal ein System, anders als eine Kolonie.

Eine dritte Möglichkeit wäre, dass eine Allianz feste, ja ich sags mal weil einige die dinger vermissen, Stationen oder ähnliches in ein System bauen um dementsprechend ein System in dessen Besitz zu bringen. 

Welche Features dann Allianzterritorien auf der anderen Seite hätten, wäre dann natürlich wieder eine andere Überlegung.

**Comment by usox** [comment]
Also ich bin grundsätzlich nicht unbedingt ein Freund von solchen Territorien in Spielerhand. Was nämlich passiert (und das hat die Vergangenheit schon oft genug gezeigt) ist, dass aggressive Allianzen beginnen werden, andere Spieler aus diesen Territorien zu vertreiben. Erfahrungsgemäß gibt es dann auch kaum Gegenwehr durch andere Allianzen - am Ende verlieren die Anfänger,  Einzelsiedler und auch Allianzen - da ist viel Frust dabei.

Ob und wie so etwas möglich ist, wird am Ende sowieso erstmal das Grundkonzept des Spiels festlegen. Würde man solche Territorien ermöglichen, dann nur fernab von den Startgebieten - heißt, als Spieler muss man erstmal mit großen Aufwand in diese Bereiche umziehen, neue Spieler wären nicht betroffen.
Das Gründen und Halten von solchen Territorien muss zudem mit großem Aufwand verbunden sein - da bin ich eher bei Deinem Gedanken mit den Stationen (gilt auch für die Großmächte). Da sind wir aber - wie gesagt - beim Konzept und Balancing. Also ein Thema für später...

**Comment by Huxinator** [comment]
Gut, dass gewisse Allianzen gern Spieler rausgemobbt haben wissen wir ja alle noch. Prinzipiell ist es aber so, dass dieses mobben auch unabhängig davon läuft. In der aktuell laufenden v2.6 gibt es auch den ein oder anderen der gern einfach mal frei dreht sowohl Ingame wie auch im OFF. Da muss man dann vermutlich so oder so als höhere administrative Macht oder durch irgendwelche Spielmechaniken gegenarbeiten. 

Ich hab mir das auch so gedacht, dass man prinzipiell im Gebiet der Fraktion von der man das Siedlerpatent erhalten hat, startet. Diese Gebiete sollten auch mMn fest sein bzw. zumindest ein festes Kerngebiet haben. Oder noch besser, falls die NPCs Rassen-Allianzen gründen, dann sollten die daran geknüpft sein. Diese NPC-Rassen-Allianzen können dann auch nur Territorien von anderen NPC-Rassen-Allianzen angreifen. Bei anderen Allianzen sollten die sich sonst raus halten. 
Der neutrale Raum ist dann sozusagen offen für alle anderen Allianzen um dort ihre Territorien aufzubauen. 

Einen Umzug selbst sollte man dann natürlich auch nur machen, wennn einen die eigene Allianz unterstütz.

Prinzipiell könnte man hierauf im Spielkonzept einen Schwerpunkt setzen. Die meisten ziehen ja sowieso gern ihre imaginären Grenzen. Warum dann nicht gleich echte Territorien. Das ergibt sicher gute RPs wenn man um das ein oder andere System erbittert kämpfen muss.

**Comment by Bielhelm** [comment]
Ähnliches hat in 2.6 nicht funktioniert.  Und neu ist das ganze nicht, sondern im groben aus "Star Trek - Alien Domain" abgekupfert. 
Als zusätzliches "Extra" ingame , daß mit eigener Teilengine läuft, und nur die Ergebnisse aus diesen Kämpfen in STU reinbringt, vielleicht denkbar. 
Ähnlich "Hades Star" am Android, wo entsprechende kurz vor der Explosion stehende Planeten in einem weissen Stern als eine Art Schlachtfeld mit je einem realen Schiff extra generiert werden und nur einer von 6 überlebt, der dann irgendeinen Bonus zugesteckt bekommt, der im realen STU benutzt werden kann, aber nicht mit realen Verlusten ingame zu kämpfen hat

**Comment by Huxinator** [comment]
Naja, in STU 2.6 sind diese Rassenterritorien ja dann schon schon nicht sehr ähnlich zu dem was ich hier vorgeschlagen habe. Was sich da ausgedacht wurde, ist nichts halbes und nichts ganzes. Eigentlich sind es nur farbliche markierungen gewesen (wie wir es jetzt in der v3 haben) die hin und wieder ihre Farbe gewechselt haben. Es geht ja eben darum, so ein Feature auch mal zu Ende zu denken mit all seinen Facetten und nicht einfach so ein unfertiges Ding da hin zu klatschen wie in v2.6

Alien Domain kenn ich nicht
