### ISSUE TITLE
Torpedotypen im Schiffshud anzeigen

### ISSUE THREAD

**Issue by LWU86** [st-universe/core#393]
Aus dem Forum:

Hallo zusammen,

eine kleine Idee meinerseits: Im Schiffs "Cockpit" sollte ersichtlich sein was für ein Torpedotyp geladen ist.
Man sieht nur "Torpedos" und die Anzahl. Den Typen sieht man nur über das Schiffsmanagement vom Plani aus.
Vielleicht sollte da anstatt "Torpedos" dann "Photonentorpedos" oder "Plasmatorpedos" oder was auch immer stehen.

**Comment by Huxinator** [comment]
e0afc0b
