### ISSUE TITLE
Spielstart-Aenderungen

### ISSUE THREAD

**Issue by usox** [st-universe/core#4]
Der Spielstart ist in meinen Augen erstmal ganz gut gelungen. Durch die direkte Auswahl eines Planeten bleibt einem die Suche und damit Frust erspart. Da man jedoch kein Schiff hat, ist man gerade zu Anfang schon arg eingeschränkt was durchaus zu Langeweile führen kann.
Die Frage, die ich mir daher stelle: Würde es nicht Sinn machen, zusätzlich zur Kolonie gleich ein Einsteigerschiff zu erzeugen, welches - einigermaßen autark - am Anfang gleich mal für Erkundung, etc genutzt werden kann...?

**Comment by LWU86** [comment]
Das halte ich für ne gute Idee. Je mehr die Leute zum Start im Spiel machen können, desto höher die Chance, daß auch absolute Neulinge nicht gleich wieder die Lust verlieren.

**Comment by usox** [comment]
Man muss da im Grunde ein paar Dinge in Betracht ziehen. Grundsätzlich hätte ich am Anfang gerne schneller die Möglichkeit, einfache Schiffe zu bauen - gerne auch generische (=ohne Fraktion) Designs, ohne Warpkern mit minimalen Bewaffnung - aber ausreichen, um im eigenen Sternensystem unterwegs zu sein

**Comment by Bielhelm** [comment]
Mit solchen Standart-Designs könnte man zwar auch später als reiner Händler arbeiten, jedoch wäre solch ein generisches Design von Vorteil. ( In STU 2.6 wurden  "einfache Schiffe" verwirklicht, die von vielen generisch baubar sind, aber aus zuviel Module bestehen, damit das noch Spaß macht)

Ich schlage eiskalt: 
- "Pakled Frachter" für Handel (*)
-  "Drohnen" oder "Shuttles" zur Erforschung  (*)
für die Idee vor.

* Denn das Tech-Niveau dürfte jede x-beliebige Rasse in Star Trek schon immer besessen haben^^.

**Comment by usox** [comment]
Ja, ich denke ein einfacher Frachter macht definitiv Sinn - es ist schon etwas sehr fad am Anfang und man kriegt auch keine Waren mit dem Kolonieschiff transportiert - mit einem generischen Design muss man da auch nicht so viel rumtun (vorerst).

Grundsätzliche Idee:
- Deuterium betrieben, nicht warpfähig
- Im Hangar bau- und startbar
- Benötigt keine ausgebildete Crew (wie Kolonisationsschiff)
- Muss erforscht werden, idealerweise in Verbindung mit Kolonisationsschiff
- Hat keinen Transporter, Waren muessen ueber Kolonie transportiert werden (Diebstahlschutz fuer Newbies)

Alternative: Das Kolonisationsschiff bekommt einen groesseren Frachtraum

**Comment by LWU86** [comment]
Dem Koloschiff nen größeren Frachtraum zu geben, wäre wahrscheinlich die simplere Möglichkeit.
