### ISSUE TITLE
Abfallentsorgung für Lager

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#52]
Lager sollten (vielleicht gegen Energie) Ressourcen auf Kolonien vernichten können. Bspw. wenn man irgendeinen Müll wie übermäßig viel Nahrung, Iridium, oder ähnliches im Lager hat und es sonst nicht loswerden kann. Oder jemand meint, seine Kolonie mit Erzen voll zu spamen sodass das Lager voll ist.

**Comment by usox** [comment]
Balancing, Handel und Kreativität.
Wenn jemand zu viel Krams produziert, dann muss er damit umgehen - auf die ein oder andere Weise. Das Spiel sollte den Spieler nicht nötigen, zu viel Kram zu produzieren (v.a. den, den er nicht braucht). Wenn doch, muss die Spielmechanik `realistische` Wege haben um die Waren loszuwerden (oder eben gar nicht erst entstehen zu lassen).

Ich hatte vor langer Zeit mal die Idee, einen Warenankauf an Handelsposten oder ähnlichem einzubauen, bei dem man gegen Währung seine Waren zu einem sehr, sehr schlechten Kurz entsorgen kann.

Oder eben die alternative: Mit dem Frachter in die Sonne :)
Vielleicht beschränken wir auch irgendwann mal die Rohstoffe pro Planet...mhm...

**Comment by Huxinator** [comment]
Na überschüssige Waren lassen sich doch sicher für die Ingame Währung die eingeführt werden könnte billig verkaufen
