### ISSUE TITLE
Vorlauf für Kriegserklärungen sofern diplomatische Beziehungen bestehen

### ISSUE THREAD

**Issue by usox** [st-universe/core#6]
Derzeit ist es ja so, dass eine Kriegserklärung zwischen Allianzen quasi `sofort` gültig ist und somit jederzeit teils extreme Überraschungsangriffe ermöglicht.
Was haltet ihr davon, wenn man hier eine Pufferzeit von z.B. 24 Stunden einbaut - sprich, man kann den Krieg erklären aber die Auswirkungen werden erst 24 Stunden später aktiv. Das bezieht sich natürlich nur auf Allianzen, die eine bestehende Beziehung haben nicht auf Allianzen die untereinander keinen diplomatischen Kontakt halten.

**Comment by LWU86** [comment]
Grundsätzlich in Ordnung. Allerdings fände ich 24 Stunden etwas zu viel. 12 sollten ausreichend sein.

**Comment by usox** [comment]
Vielleicht muss man da auch generischer denken wie z.B., dass allgemein binnen 24 Stunden keine Aenderung bestehende Beziehungen moeglich ist...

**Comment by Bielhelm** [comment]
Das Überraschungsmoment hat tatsächlich in STU lange Tradition. Ich finde, man könnte damitl brechen. Ich finde auch, daß ein halber Tag ausreichend sein dürfte. 
Jedoch wäre es noch viel besser, wenn sämtliche Mitglieder einer Allianz per Email über die Kriegserklärung informiert werden könnten, denn damit wäre die Frage für den Zeitraum des Vorlaufes nämlich erledigt.
