### ISSUE TITLE
Administrative Re-Aktivierung von Spielerkonten

### ISSUE THREAD

**Issue by Bielhelm** [st-universe/core#65]
Aus aktuellem Anlass an anderer Stelle, hab ich mir überlegt, ob es wohl möglich ist, Spielerkonten die entweder absichtlich oder unabsichtlich (durch höhere Gewalt oder z.B. technische Probleme) gelöscht worden sind, durch die Administration nachträglich weitere 30 Tage nochmal auf Anfrage des Spielers mit Begründung reaktiviert werden könnten? Sozusagen als "Sicherung"?

**Comment by usox** [comment]
Also man muss klar sagen, dass `geloescht` wirklich `geloescht` bedeutet - die Daten sind weg. Falls jemand seinen Account selbtstaendig loescht (inklusive Nachfrage per eMail und Bestaetigungs-Link), warum sollte man das dann nicht durchfuehren?
Gleiches gilt fuer eine Loeschung nach Inaktivitiaet. Weshalb sollte man die Daten nicht loeschen, wenn jemand z.B. 30 Tage inaktiv ist?

**Comment by Bielhelm** [comment]
Servus,

konkreter: ( auch wenn ich wieder mal ein wenig auf das Schwesterspiel hinweise) 

Weil es wegen höherer Gewalt oder technischen Problemen mal zu einem längerfristigen Ausfall kommen kann und dann ist eine Löschung der Daten nach 30 Tagen Abstinenz eben auch nicht mehr rückgängig gemacht werden kann. 

 Das es eine zusätzliche "Sicherung" der Spielerkonten für alle Faelle zumindest für ein weiteres Monat geben könnte, wäre der Ansatz gewesen, um die Spieler in 2.6 (wie bekannt :fehlendes Zertifikat) zu behalten. 

Das ist ja zum momentanen Stand so nicht möglich.

**Comment by usox** [comment]
Ob man jemals so etwas wie den "damaligen" Urlaubsmodus braucht, wird sich zeigen. Ich werde hier jetzt keine "wir brauchen xyz, weil woanders ist abc passiert" Diskussionen fuehren. Fakt ist: Sollte das Spiel aufgrund technischer Probleme nicht funktionieren, werden auch keine Loeschungen durchgefuehrt. Wenn das Spiel ne Woche ausfaellt, koennen wir den Laden auch gleich zusperren da wir dann anscheinend nicht in der Lage sind, es zu betreiben.
