### ISSUE TITLE
bbcodes für das KN und PN

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#74]
Man könnte wieder BBcodes für das KN und die Privatnachrichten einführen. Also Bspw. [b] für **fette Schrift** und [i] für _kursive Schrift_.

Zur besseren unterscheidung könnte man auch ähnlich wie bei der Allianzseite einige Befehle wie [ON] oder [OFF] einbauen welche in privaten Nachrichten dann durch soetwas wie ein farbiger Text "offgame Nachricht:" bzw. "ingame-Nachricht:" anzeigen.

**Comment by LWU86** [comment]
Gerade die BBCodes fürs KN vermisse ich auch sehr. 
Die funktionieren übrigens in der Siedlerbeschreibung genauso wenig.

**Comment by usox** [comment]
Das Problem hierbei ist folgendes:
Ich moechte nicht, dass alle BB-Codes an jeder Stelle verfuegbar sind. So will ich keine bunten KN-Postings oder Regenbogen-Allianzseiten. Nun ist es aber so, dass der BBCode Parser etwas ist, was tief im System verankert ist und ich nicht an verschiedenen Stellen extra konfigurieren kann - zumindest Stand jetzt nicht.
Ich sehe das daher mehr als Zukunftsthema

**Comment by usox** [comment]
Vermutlich koennte die Loesung hier sein, eine eigene Parser-Instanz fuer diese Falle einzubauen

**Comment by usox** [comment]
So, es sind jetzt mal eine beschränkte Anzahl von BB-Codes im KN aktiv. Man kann ueberlegen, ob man die spaeter auch in privaten Nachrichten nutzen kann. So lang erstmal zu
