### ISSUE TITLE
Datenbank /Planetenklassenanzeige

### ISSUE THREAD

**Issue by ghost** [st-universe/core#76]
Beim Anklicken auf bereits erforschte Planetenklassen kommt leider nichts mehr danach. Nicht mal ein Fehler. 

![Screenshot_20191030_092855](https://user-images.githubusercontent.com/52820159/67855699-385bc700-fb13-11e9-9b31-bbf1f7569eb5.jpg)

**Comment by usox** [comment]
Hierfür gabs noch so recht keine Idee, was man machen kann. Kann man später mal adressieren, wenn man die Ingame-DB etwas aufwertet
