### ISSUE TITLE
Pfad für Allianzlogo falsch?

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#78]
Nachdem man ein Allianzlogo hochgeladen hat und es per $ALLIANCE_BANNER in die Beschreibung eingebunden hat, wird eine fehlende Grafik angezeigt. Siehe Allianzseite der Imperialen Union.

**Comment by Huxinator** [comment]
Auch nochmal im Forum:
https://forum.stuniverse.de/viewtopic.php?f=9&t=25&p=61#p62

**Comment by usox** [comment]
Ja, die wurden auch in den user avatar pfad gespeichert. Nach dem Fix muessen die Allianzbilder neu hochgeladen werden.
