### ISSUE TITLE
Zeitepoche

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#80]
Mir ist gerade aufgefallen, dass im KN als Datum das Jahr 2019 angezeigt wird.
Wir sollten vielleicht auf ein Jahr springen, dass hinter dem Dominion Krieg liegt?
2389? 2399? 2409?

**Comment by usox** [comment]
Ich denke, das koennen wir uns ueberlegen, wenn wir mal ein Grundsetting fuer das Spiel haben :)

**Comment by LWU86** [comment]
2.6 spielte zuletzt 2393, daran sollten wir idealerweise anknüpfen.
