### ISSUE TITLE
Crewverlust

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#84]
Wir sollten uns mal überlegen, was mit der Crew von zerstörten Schiffen passiert.
Aktuell ist es so, dass wenn ein Schiff zerstört wird, die Crew schlichtweg wieder als verfügbare Crew zurück gestuft wird. Heißt also dass man diese dann theoretisch direkt von der Kolonie aufs nächste Schiff transferieren kann.

Meine Idee wäre es, neben den Trümmerfeldern noch Rettungskapseln auftauchen zu lassen. Mit einem Zufallswert können auf diesen Rettungskapseln irgendwas zwischen 0% und sagen wir mal 80% der Crew für einige Ticks gelagert sein. Diese Rettungskapseln sollen von mir aus von fremden Spielern auch zerstört werden können. Sind einige Ticks verstrichen und man hat die Crew nicht gerettet, sterben die Crewmitglieder einfach und fallen somit aus der Datenbank.
Alternativ rettet man mit einem Schiff die Crew und bringt diese wieder zurück zu einer Kolonie von der aus man die Crew wieder auf neue Schiffe transferieren kann. Hierbei sollte man beachten, dass vielleicht der Crewüberschuss auf dem rettenden Schiff einen Energiemalus (höhere Replikatorkosten usw) verursachen könnte.
Was man sich auch überlegen könnte, wäre ob andere Siedler die Crew aus Rettungskapseln aufbringen könnte. Diese könnten dann entweder als Kriegsgefangene gelagert werden (wodurch vielleicht die Crew (beim Siedler welchem die Crew ursprünglich gehörte) weiterhin die Crew in der globalen Crewanzeige dazu addiert wird und man sich diese zurückerhandeln muss. Oder der Siedler welche die Crew aufnimmt integriert diese einfach ins eigene Crewsystem. Bzw. wenn es ein ganz netter Siedler ist, kann er ja die Crew dem ursprünglichem Siedler zurück bringen.

**Comment by LWU86** [comment]
Alles tolle Ideen. Wär klasse, wenn die umgesetzt werden könnten.

**Comment by usox** [comment]
@Huxinator Das ist so nicht ganz richtig, was Du da erzaehlst und ich vermute mal, dass einige der Fehleinschaetzungen auf deiner gespawnten Galaxy aus dem Live-System beruhen?

Fakt ist: Wird ein Schiff zerstoert, ist die Crew tatsaehlich noch `am Leben` und ist in Rettungskapseln auf dem Schiff (afaik sieht man die aber nicht). Wird jetzt ein Schiff von einem Spieler (also auch von einem selbst) gescant, werden die Rettungskapseln automatisch dem Spieler zuruecktransferiert, dem das Schiff urspruenglich gehoerte.

Ich empfehle dringend, Tests mit selbst gebauten Schiffe durchzufuehren (im test-system idealerweise, da haben wir ja auch Express-Ticks damits schneller voran geht) als mit anderweitig erhaltenen Schiffen.

**Comment by Huxinator** [comment]
Jip mein Fehler. 
Dann bleibt nurnoch die Idee mit den Crews richtig retten durch verschiedene Spieler bzw Kriegsgefangene
