### ISSUE TITLE
bb-Code Erweiterung 

### ISSUE THREAD

**Issue by ghost** [st-universe/core#9]
Kann man eine Erweiterung des BB-Codes durchführen?
[h1],[p], [size],[highlight],[list],[quote]
- im Komm
 - Im Profil ist das tag [img] nicht erlaubt, kann man das freischalten?

**Comment by usox** [comment]
Da muss man selektiv mal schauen. Auch hier ist wieder das Missbrauchspotential gegeben, weshalb wir da sehr streng sein werden/muessen. Vereinzelt kann man da mal gucken, was Sinn macht (und v.a. an welcher Stelle)
