### ISSUE TITLE
Fehler-BoP bei Schiff zu Schiff Transport

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#91]
Aus dem Forum: https://forum.stuniverse.de/viewtopic.php?f=9&p=198#p198

von Richards » Fr Nov 15, 2019 6:56 am
Ich kann nicht sagen, inwieweit das ein Bug oder vielleicht schon bekannt ist, ich schreibe es trotzdem mal hier rein.

Version: 804

Vorgeschichte: Mich hat heute Nacht der NPC Kot-las-tsor (Id 15) besucht und zuerst meinen Frachter etwas entführt und dann mit Sonderwaren befüllt (Mal danke dafür, bis auf die Tribbles, bei denen bin ich Klingone). Auf dem Heimweg stolpere ich wieder über sein Schiffchen und denke mir "Hey, gib ihm doch die Tribbles zurück" (habe ich erwähnt, dass ich die nicht mag?). Also versuche ich, es ihm zurück zu geben und kriege den Fehler-BoP. Und zwar sowohl beim Hin- und Wegbeamversuch

Ich habe natürlich hinterher gesehen, dass der Zielfrachter die Schilde oben hat, deswegen kann der Fehler was damit zu tun haben. Zum Gegentest habe ich meinen Frachter nebenhin gestellt und die Schilde angeknipst. Er kann ja mal versuchen, mir die Tribbles zu klauen (Ich glaube, ich mag keine Tribbles ;) ).

----------------------------------
mit dem Pakled Schiff getestet. Es liegt tatsächlich an den aktivierten Schilden.

**Comment by usox** [comment]
Problem ist, dass das Schiff auswaehlbar obwohl es die Schilde an hatte bzw. diese im gleichen Moment aktivierte
