### ISSUE TITLE
Anzeigefehler im Orbitalmanagement

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#92]
Im Orbitalmanagement einer Kolonie sind die Anzeigen von fremden Schiffen zum einem verschoben (Batterie, Warpkernfüllung) und zum anderen steht bei fremden Schiffen weder zu wie viel die Batterie geladen ist, noch in wie weit der Warpkern gefüllt ist. Beides lässt sich jedoch laden.

Bild:
Oberes Schiff gehört mir, unteres einem anderen Siedler
![orbitalmanagement](https://user-images.githubusercontent.com/52821266/68970881-9ca3a980-07e8-11ea-985c-a80972e6ca58.PNG)

**Comment by usox** [comment]
Dass die Anzeige bei fremden Schiffen fehlt ist tatsaechlich Absicht. Man soll die Information zum Status fremder Schiffe nicht bekommen
