### ISSUE TITLE
Zu wenig EPS & zu viele freie Arbeiter

### ISSUE THREAD

**Issue by Huxinator** [st-universe/core#97]
Aus dem Forum: https://forum.stuniverse.de/viewtopic.php?f=9&t=79

	von Android82 » Fr Nov 22, 2019 10:17 pm
Guten Abend zusammen :)

Auf meiner Kolonie dürfte es wohl gleich 2 Bugs geben.

Zuerst scheint sich der EPS-Wert meiner Kolonie falsch zu berechnen.
Vorhanden sind die Koloniezentrale (+96 EPS), 5x Solarzellen (+80 EPS) und 10x Gezeitenkraftwerke (+160 EPS).
Insgesamt müsste der EPS-Speicher also 336 EPS groß sein, tatsächlich sind es allerdings "nur" 320, es fehlen 16 EPS.
Nicht wirklich störend, bauen kann ich, aber korrekt eben auch nicht ;)

Zweitens hab ich ausgerechnet, dass auf meiner Kolonie nur 5 Arbeiter frei sein dürften.
Frei sind allerdings bei allen Gebäuden aktiv aber 35.
Interessant ist dabei auch, wenn ich alle Gebäude deaktiviere, habe ich plötzlich 702 Arbeiter.
In die Häuser + Koloniezentrale passen aber nur 8x84 = 672.
Sobald ich die Häuser + Koloniezentrale wieder aktiviere tritt dieses Limit von 672 Arbeitern auch ein.
Aktiviere ich dann auch die Industrie + Farmen + etc hab ich 30 Arbeiter mehr frei als es sein sollten (die erwähnten 35).

Beides müsste aus den angehängten Screenshots ersichtlich sein.
Siedler-ID ist 123, Kolo-ID müsste (wenn ich da recht schaue) 360 sein.

Tante Edith meldet noch:
Die Mond-Kolonie (ID: 4171) berechnet alles korrekt, sowohl Arbeiter und EPS sind korrekt berechnet
![grafik](https://user-images.githubusercontent.com/52821266/69475958-c43fd680-0dd3-11ea-9310-c02201812068.png)
![grafik](https://user-images.githubusercontent.com/52821266/69475961-c9048a80-0dd3-11ea-8a21-62e4d434eefe.png)

**Comment by usox** [comment]
Das muss man mal im Auge behalten. Korrigieren kann man das natuerlich, den Ausloeser dafuer brauchen wir allerdings trotzdem mal...
